version: '3.9'
services:
  frontend:
    build: ./ngcash_frontend
    restart: 'on-failure'
    ports:
      - 3000:3000
    container_name: app_frontend
    command: "npm start"
    depends_on:
      - backend
  backend:
    build: ./ngcash_backend
    restart: 'on-failure'
    ports:
      - 3001:3001
    container_name: app_backend
    command: "npm start"
    volumes:
      - './ngcash_backend/build:/app/build'
    depends_on:
      - db
      - migrations
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DB_HOST=db
      - DB_NAME=ngcash
      - DB_PORT=5432
      - SECRET=senhasecreta123
  migrations:
    build: ./ngcash_backend
    restart: 'on-failure'
    container_name: migrations
    command: "npm run db:reset"
    volumes:
      - './ngcash_backend/build:/app/build'
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DB_HOST=db
      - DB_NAME=ngcash
      - DB_PORT=5432
      - SECRET=senhasecreta123
  db:
    image: postgres
    container_name: db
    ports:
      - 3002:5432
    environment:
      - POSTGRES_PASSWORD=postgres123
    restart: 'on-failure'